name: personal-website-ci

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix:
                node-version: [22]
                threads: [4]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install Docker
              run: make install-docker

            - name: Install MongoDB
              run: make install-mongo

            - name: Start MongoDB
              run: make start-mongo

            - name: Install Depedencies
              run: pnpm i

            - name: Generate Env Type Definitions
              run: make generate-environment-type-definition

            - name: Create Environment Variable
              run: make copy-env-testing

            - name: Lint Code
              run: make lint

            - name: Typecheck Code
              run: make typecheck

            - name: Check Format Code
              run: make format-check

            - name: Unit test & API test
              # running test will also execute `build`
              run: make pretest-ci && make test

            - name: Generate sitemap and webmanifest
              run: make generate-webmanifest
